chore: add dependabot configuration (#265)
fi3ework/vite-plugin-checker pull request #315
Opened 2024-04-12 14:35 UTC by jhoermann

See [Configuring Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) for more info.

2024-04-17 09:03 UTC, jhoermann commented
Added https://github.com/fi3ework/vite-plugin-checker/pull/311/commits/f6201867a936ebacf02db98789790670003660be to also fix #264 @fi3ework.

2024-04-30 15:21 UTC, jhoermann commented
Github has added `directories` now: https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/. So I'll change this PR accordingly.

2024-07-01 16:34 UTC, jhoermann commented
I added the `directories` option now so that it'll automatically check all `package.json`s of this repo. @fi3ework if you want to have a look, it can also be reduced to the main directories (e.g. exclude the playground ones).

2024-07-02 05:09 UTC, fi3ework commented
Thanks you! It's seems general good for now, we could change if needed in the future.

2024-07-02 05:12 UTC, fi3ework approved these changes

2024-07-02 05:18 UTC, fi3ework requested changes
Setting to `weekly` fine will be reasonable, `daily` is somehow too noisy.

2024-07-02 05:18 UTC, fi3ework commented on .github/dependabot.yml
> +      interval: 'daily'
```suggestion
      interval: 'weekly'
```

2024-07-02 05:18 UTC, fi3ework commented on .github/dependabot.yml
> +      interval: 'daily'
weekly
```suggestion
      interval: 'weekly'
```

2024-07-02 07:41 UTC, merged

2024-07-02 08:03 UTC, jhoermann commented
Thanks for the merge @fi3ework! Nice to see some action again on this repo. Adding the `dependencies` label would make sense now as the dependabot tries to apply it and can't find it.